config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  resources :resturants do
  collection do
    get 'search'
  end
    resources :reviews, except: [:show, :index]
  end

  get 'pages/about'

  get 'pages/contact'

  root 'resturants#index'

end

app/models/resturant.rb
class Resturant < ActiveRecord::Base
  mount_uploader :image, ImageUploader

  searchkick

  has_many :reviews

  validates :name, :address, :phone, :website, :image, presence: true
  validates :phone, format: { with: /[\d -]{7,10}/,
    message: "format is wrong" }
  validates :website, format: { with: /\Ahttps?:\/\/.*\z/,
    message: "must start with http:// or https://" }
  validates :address, format: { with: /[\d,]+/,
    message: "Formated wrong" }
end

app/controllers/resturants_controller.rb
class ResturantsController < ApplicationController
  before_action :set_resturant, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:search, :index, :show]
  before_action :check_user, except: [:search, :index, :show]

  def search
    if params[:search].present?
      @resturants = Resturant.search(params[:search])
    else
      @resturants = Resturant.all
    end
  end

# GET /resturants
  # GET /resturants.json
  def index
    @resturants = Resturant.all
  end

  # GET /resturants/1
  # GET /resturants/1.json
  def show
    @reviews = Review.where(resturant_id: @resturant.id).order("created_at DESC")
    if @reviews.blank?
      @avg_rating = 0
    else
      @avg_rating = @reviews.average(:rating).round(2)
    end
  end

  # GET /resturants/new
  def new
    @resturant = Resturant.new
  end

  # GET /resturants/1/edit
  def edit
  end

  # POST /resturants
  # POST /resturants.json
  def create
    @resturant = Resturant.new(resturant_params)

    respond_to do |format|
      if @resturant.save
        format.html { redirect_to @resturant, notice: 'Resturant was successfully created.' }
        format.json { render :show, status: :created, location: @resturant }
      else
        format.html { render :new }
        format.json { render json: @resturant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /resturants/1
  # PATCH/PUT /resturants/1.json
  def update
    respond_to do |format|
      if @resturant.update(resturant_params)
        format.html { redirect_to @resturant, notice: 'Resturant was successfully updated.' }
        format.json { render :show, status: :ok, location: @resturant }
      else
        format.html { render :edit }
        format.json { render json: @resturant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /resturants/1
  # DELETE /resturants/1.json
  def destroy
    @resturant.destroy
    respond_to do |format|
      format.html { redirect_to resturants_url, notice: 'Resturant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_resturant
      @resturant = Resturant.find(params[:id])
    end

    def check_user
      unless current_user.admin?
        redirect_to root_url, alert: "Sorry, only admins can do that!"
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def resturant_params
      params.require(:resturant).permit(:name, :address, :phone, :website, :image)
    end
end

app/helpers/resturants_helper.rb
module ResturantsHelper
end

app/views/resturants/_form.html.erb
<%= form_for(@resturant, :html => {multipart: true}) do |f| %>
  <% if @resturant.errors.any? %>
    <div id="error_explanation", class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h4><%= pluralize(@resturant.errors.count, "error") %> prohibited this restuarant from being saved:</h4>

      <ul>
      <% @resturant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :address %><br>
    <%= f.text_field :address, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :phone %><br>
    <%= f.text_field :phone, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :website %><br>
    <%= f.text_field :website, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :image%><br>
    <%= f.file_field :image, class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/resturants/edit.html.erb
<h1>Editing Resturant</h1>

<%= render 'form' %>

<%= link_to 'Show', @resturant, class: "btn btn-link" %> |
<%= link_to 'Back', resturants_path, class: "btn btn-link" %>

app/views/resturants/index.html.erb
<p id="notice"><%= notice %></p>

<div class="jumbotron">
<h2>Header for Yelpdemo!!!</h2>
<h3>Smaller text ander the header.<br>
    Some very important text.</h3>
</div>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Phone</th>
      <th>Website</th>
      <% if user_signed_in? && current_user.admin? %>
        <th colspan="2"></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @resturants.each do |resturant| %>
      <tr>
        <td><%= link_to resturant.name, resturant %></td>
        <td><%= resturant.address %></td>
        <td><%= resturant.phone %></td>
        <td><%= link_to resturant.website, resturant.website %></td>
        <% if user_signed_in? && current_user.admin? %>
          <td><%= link_to 'Edit', edit_resturant_path(resturant), class: "btn btn-link" %></td>
          <td><%= link_to 'Destroy', resturant, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-link" %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if user_signed_in? && current_user.admin? %>
  <%= link_to 'New Resturant', new_resturant_path, class: "btn btn-link" %>
<% end %>

app/views/resturants/new.html.erb
<h1>New Resturant</h1>

<%= render 'form' %>

<%= link_to 'Back', resturants_path, class: "btn btn-link" %>

app/views/resturants/search.html.erb
<table class="table table-hover table-condensed">
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Phone</th>
      <th>Website</th>
      <% if user_signed_in? && current_user.admin? %>
        <th colspan="2"></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @resturants.each do |restaurant| %>
      <tr>
        <td><%= link_to restaurant.name, restaurant %></td>
        <td><%= restaurant.address %></td>
        <td><%= restaurant.phone %></td>
        <td><%= link_to restaurant.website, restaurant.website %></td>
        <% if user_signed_in? && current_user.admin? %>
          <td><%= link_to 'Edit', edit_resturant_path(restaurant), class: "btn btn-link" %></td>
          <td><%= link_to 'Destroy', restaurant, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-link" %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/resturants/show.html.erb
<div class="row">
  <div class="col-md-3">
    <%= image_tag @resturant.image_url %>

    <h2>
      <%= @resturant.name %>
    </h2>

    <div class="star-rating" data-score= <%= @avg_rating %> ></div>
    <p><%= "#{@reviews.length} reviews" %></p>

    <p>
      <strong>Address:</strong>
      <%= @resturant.address %>
    </p>
    <p>
      <strong>Phone:</strong>
      <%= @resturant.phone %>
    </p>
    <p>
      <strong>Website:</strong>
      <%= link_to  @resturant.website, @resturant.website %>
    </p>

    <% if user_signed_in? %>
      <%= link_to "Write Review", new_resturant_review_path(@resturant), class: "btn btn-primary" %>
    <% end %>

    <br>
    <br>

    <iframe
        width="230"
        height="230"
        frameborder="0" style="border:0"
        src="https://www.google.com/maps/embed/v1/search?key=AIzaSyB8guSI_ipDB3-f62qrGsgy6u_DoFpbW4E&q=<%= @resturant.address.gsub(/[, ]/,'+') %>&language=ru">
     </iframe>
  </div>

  <div class="col-md-9">
    <% if @reviews.blank? %>
      <h3>No reviews yet. Be the first to write one!</h3>
    <% else %>
      <table class="table">
        <thead>
          <tr>
            <th class="col-md-3"></th>
            <th class="col-md-9"></th>
          </tr>
      </thead>

        <tbody>
          <% @reviews.each do |review| %>
            <tr>
              <td>
                <h4>
                  <%= image_tag review.user.image_url %>
                  <%= "#{review.user.first_name.capitalize} #{review.user.last_name.capitalize.first}." %>
                </h4>
                <p><%= review.created_at.strftime("%-m/%-d/%-y") %></p>
              </td>

             <td>
                <div class="star-rating" data-score= <%= review.rating %> ></div>
                <p><%= h(review.comment).gsub(/\n/, '<br/>').html_safe %></p>

                <% if user_signed_in? %>
                  <% if (review.user == current_user) || (current_user.admin?) %>
                    <%= link_to "Edit", edit_resturant_review_path(@resturant, review) %>
                    <%= link_to "Delete", resturant_review_path(@resturant, review), method: :delete %>
                  <% end %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
  </div>
</div>

<%= link_to 'Edit', edit_resturant_path(@resturant), class: "btn btn-link" %> |
<%= link_to 'Back', resturants_path, class: "btn btn-link" %>

<script>
  $('.star-rating').raty({
    path: '/stars',
    readOnly: true,
    score: function() {
      return $(this).attr('data-score');
    }
  });
</script>